channels:
  - conda-forge
  - defaults
  - fastai
dependencies:
  - python >=3.8,<3.9
  - pip
  # Essentials
  - deon    # Data ethics checklist
  - numpy
  - scipy
  - pandas
  - lxml
  # Jupyter - Lab, Notebook, ipykernel
  - jupyterlab 
  - ipykernel
  # Streamlit and friends
  - streamlit
  # Pip installs
  - pip:
    - -e .


# Currently choosing to be a Python 3.8 environment
